apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hackathon-app.fullname" . }}
  labels:
    {{- include "hackathon-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ include "hackathon-app.name" . }}"
  template:
    metadata:
      labels:
        app: "{{ include "hackathon-app.name" . }}"
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017/test"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 5