apiVersion: v1
kind: Service
metadata:
  name: {{ include "hackathon-app.fullname" . }}
  labels:
    {{- include "hackathon-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.node.port }}
  selector:
    app: "{{ include "hackathon-app.name" . }}"
